#include "rnd/sfx.h"

#include "rnd/savefile.h"
#include "rnd/settings.h"
#include "z3d/z3DVec.h"  // ARR_SIZE

#if defined ENABLE_DEBUG || defined DEBUG_PRINT
#include "common/debug.h"
#endif

namespace rnd {
  namespace {
    enum class SfxCategory : u8 {
      Excluded,
      Player,
      Item,
      Environment,
      Enemy,
      System,
      Voice,
    };

    struct SfxCategoryRun {
      u16 first;  // index from SFX_BASE; the run lasts until the next entry
      SfxCategory category;
    };

    // Generated by gen_sfx_categories.py.
    constexpr SfxCategoryRun kSfxCategoryRuns[] = {
        {0x000, SfxCategory::Excluded},    {0x001, SfxCategory::Player},      {0x00E, SfxCategory::Excluded},
        {0x00F, SfxCategory::Player},      {0x081, SfxCategory::Excluded},    {0x084, SfxCategory::Player},
        {0x085, SfxCategory::Excluded},    {0x0B1, SfxCategory::Player},      {0x0B6, SfxCategory::Excluded},
        {0x0BC, SfxCategory::Player},      {0x0BD, SfxCategory::Excluded},    {0x0C0, SfxCategory::Player},
        {0x0C3, SfxCategory::Excluded},    {0x0C4, SfxCategory::Player},      {0x0CC, SfxCategory::Environment},
        {0x0CD, SfxCategory::Player},      {0x161, SfxCategory::Environment}, {0x162, SfxCategory::Player},
        {0x171, SfxCategory::Environment}, {0x172, SfxCategory::Player},      {0x1E7, SfxCategory::Item},
        {0x256, SfxCategory::Environment}, {0x277, SfxCategory::System},      {0x278, SfxCategory::Environment},
        {0x2BE, SfxCategory::Item},        {0x2BF, SfxCategory::Environment}, {0x2DE, SfxCategory::Player},
        {0x2DF, SfxCategory::Environment}, {0x466, SfxCategory::Enemy},       {0x467, SfxCategory::Environment},
        {0x468, SfxCategory::Enemy},       {0x76C, SfxCategory::System},      {0x7B2, SfxCategory::Environment},
        {0x7B3, SfxCategory::System},      {0x7E5, SfxCategory::Excluded},    {0x7F9, SfxCategory::Voice},
        {0x985, SfxCategory::Excluded},    {0x995, SfxCategory::Enemy},       {0xA34, SfxCategory::Environment},
    };

    // Names ending in _LEVEL: held by the object making them and replayed every frame. Nearly all are
    // scene ambience (windmill, waterwheel, magma, ice melt) whose data is only loaded in that scene,
    // so they are left alone rather than swapped for one another scene's.
    constexpr u16 kSfxContinuous[] = {
        0x0D1, 0x0D2, 0x0D3, 0x0D4, 0x0D5, 0x0D6, 0x0D7, 0x0D8, 0x0D9, 0x0DA, 0x0DB,
        0x0DC, 0x0DE, 0x0E0, 0x241, 0x261, 0x288, 0x291, 0x2DB, 0x359, 0x371, 0x39A,
    };

    // Link's voice: six 0x20-entry sets from VO_LI_SWORD_N (0x7F9), one per form. The offsets are the
    // voice field (+0xF8) of the player form table at 0x68D988 -- Fierce Deity 0x00, Human 0x20,
    // Deku 0x80, Zora 0xA0, Goron 0xC0 -- plus the 0xE0 emitFormSpecificSoundForPlayer uses for mask
    // 0x13. Their names come from Ocarina of Time, so most read VO_DUMMY_* or VO_NAVY_*.
    constexpr u16 kLinkVoiceBase = 0x7F9;
    constexpr u16 kLinkVoiceSetSize = 0x20;
    constexpr u16 kLinkVoiceOffsets[] = {0x00, 0x20, 0x80, 0xA0, 0xC0, 0xE0};

    constexpr u8 kNoPool = 0xFF;

    // Pools per mode: Chaos has one; Categorical has one per bank; Link Only has player, item and
    // Link's voice.
    constexpr u8 kPoolCount = (u8)SfxCategory::Voice;
    constexpr u8 kTableCount = 3;
  }  // namespace

  // One table per shuffle mode, each built the first time its mode is chosen and then kept, so a
  // sound started under either can still be found by id after the option changes. Zero means the slot
  // is not shuffled.
  static u16 sSfxTables[kTableCount][SFX_COUNT];
  static bool sSfxTableBuilt[kTableCount];

  constexpr u8 kHeldFrames = 3;
  static u16 sFrame;
  static u16 sLastPlayedFrame[SFX_COUNT];
  static u8 sPlayedRun[SFX_COUNT];
  static u32 sHeld[(SFX_COUNT + 31) / 32];

  static bool Sfx_IsHeld(u32 index) {
    return (sHeld[index / 32] >> (index % 32)) & 1;
  }

  // Counts the consecutive frames this sound has been played on, and pins it once it looks held.
  static void Sfx_TrackPlay(u32 index) {
    const u16 gap = sFrame - sLastPlayedFrame[index];
    if (gap == 1) {
      if (sPlayedRun[index] < kHeldFrames)
        sPlayedRun[index]++;
    } else if (gap != 0 || sPlayedRun[index] == 0) {
      sPlayedRun[index] = 1;
    }
    sLastPlayedFrame[index] = sFrame;
    if (sPlayedRun[index] >= kHeldFrames && !Sfx_IsHeld(index)) {
      sHeld[index / 32] |= 1u << (index % 32);
#if defined ENABLE_DEBUG || defined DEBUG_PRINT
      util::Print("SFX held %03X, no longer shuffled\n", index);
#endif
    }
  }

  static bool Sfx_IsLinkVoice(u16 index) {
    for (u16 offset : kLinkVoiceOffsets) {
      if (index >= kLinkVoiceBase + offset && index < kLinkVoiceBase + offset + kLinkVoiceSetSize)
        return true;
    }
    return false;
  }

  static bool Sfx_IsContinuous(u16 index) {
    for (u16 continuous : kSfxContinuous) {
      if (continuous == index)
        return true;
    }
    return false;
  }

  static s32 Sfx_TableForMode(u8 mode) {
    if (mode == (u8)ShuffleSFXSetting::SHUFFLESFX_CATEGORICAL)
      return 0;
    if (mode == (u8)ShuffleSFXSetting::SHUFFLESFX_CHAOS)
      return 1;
    if (mode == (u8)ShuffleSFXSetting::SHUFFLESFX_LINK_ONLY)
      return 2;
    return -1;
  }

  static u8 Sfx_GetPool(u8 mode, SfxCategory category, u16 index) {
    if (mode == (u8)ShuffleSFXSetting::SHUFFLESFX_CHAOS)
      return 0;
    if (mode != (u8)ShuffleSFXSetting::SHUFFLESFX_LINK_ONLY)
      return (u8)category - 1;
    if (category == SfxCategory::Player)
      return 0;
    if (category == SfxCategory::Item)
      return 1;
    if (category == SfxCategory::Voice && Sfx_IsLinkVoice(index))
      return 2;
    return kNoPool;
  }

  // Each pool is shuffled into itself, so every effect still plays somewhere. The draws come from
  // Hash, which is salted with the seed hash, and start from 0: the same seed and mode always give
  // the same table.
  static void Sfx_BuildTable(u8 mode, u16* table) {
    static u16 members[SFX_COUNT];

    u32 draw = 0;
    for (u8 pool = 0; pool < kPoolCount; pool++) {
      u32 count = 0;
      u32 run = 0;
      for (u16 i = 0; i < SFX_COUNT; i++) {
        while (run + 1 < ARR_SIZE(kSfxCategoryRuns) && kSfxCategoryRuns[run + 1].first <= i) {
          run++;
        }
        const SfxCategory category = kSfxCategoryRuns[run].category;
        if (category == SfxCategory::Excluded || Sfx_IsContinuous(i)) {
          continue;
        }
        const u8 sfxPool = Sfx_GetPool(mode, category, i);
        if (sfxPool == pool) {
          members[count++] = i;
          table[i] = i;
        }
      }
      for (u32 k = count; k > 1; k--) {
        const u32 j = Hash(draw++) % k;
        const u16 swapped = table[members[k - 1]];
        table[members[k - 1]] = table[members[j]];
        table[members[j]] = swapped;
      }
    }
  }

  void Sfx_Update() {
    sFrame++;
    const u8 mode = gExtSaveData.options.shuffleSFX;
    const s32 table = Sfx_TableForMode(mode);
    if (table < 0 || sSfxTableBuilt[table]) {
      return;
    }
    Sfx_BuildTable(mode, sSfxTables[table]);
    sSfxTableBuilt[table] = true;
#if defined ENABLE_DEBUG || defined DEBUG_PRINT
    util::Print("%s: built table %d for mode %u\n", __func__, table, mode);
#endif
  }

  static u32 Sfx_Remap(s32 table, u32 id) {
    const u32 i = id - SFX_BASE;
    if (table < 0 || !sSfxTableBuilt[table] || i >= SFX_COUNT || sSfxTables[table][i] == 0) {
      return id;
    }
    return SFX_BASE + sSfxTables[table][i];
  }

  extern "C" {
  void Sfx_StopByIdVanilla(void* mgr, u32 id);
  s32 Sfx_IsPlayingByIdVanilla(void* mgr, u32 id);

  // One call per sound effect, shared by both entry points. Muting is checked first and applies to
  // every id, including ones outside the table, so behaviour matches the standalone mute gates this
  // replaced.
  u32 Sfx_Filter(u32 id) {
    if (gExtSaveData.options.muteSoundEffects != 0) {
      return 0;  // suppress
    }
    const u32 index = id - SFX_BASE;
    if (index < SFX_COUNT) {
      Sfx_TrackPlay(index);
      if (Sfx_IsHeld(index)) {
        return id;
      }
    }
    const u32 remapped = Sfx_Remap(Sfx_TableForMode(gExtSaveData.options.shuffleSFX), id);
#if defined ENABLE_DEBUG || defined DEBUG_PRINT
    if (remapped != id) {
      util::Print("SFX play %03X -> %03X\n", id - SFX_BASE, remapped - SFX_BASE);
    }
#endif
    return remapped;
  }

  // A sound's handle keeps the id it was started under, and stopping by the vanilla id alone misses a
  // shuffled one. It then outlives the object that started it and writes into that object's freed
  // memory when it ends. So this stops the vanilla id and its image in every table built so far;
  // cutting an unrelated sound short is the lesser risk.
  void Sfx_StopById(void* mgr, u32 id) {
#if defined ENABLE_DEBUG || defined DEBUG_PRINT
    util::Print("SFX stop %03X (%03X %03X %03X)\n", id - SFX_BASE, Sfx_Remap(0, id) - SFX_BASE,
                Sfx_Remap(1, id) - SFX_BASE, Sfx_Remap(2, id) - SFX_BASE);
#endif
    Sfx_StopByIdVanilla(mgr, id);
    for (s32 table = 0; table < kTableCount; table++) {
      const u32 remapped = Sfx_Remap(table, id);
      if (remapped != id) {
        Sfx_StopByIdVanilla(mgr, remapped);
      }
    }
  }

  s32 Sfx_IsPlayingById(void* mgr, u32 id) {
    if (Sfx_IsPlayingByIdVanilla(mgr, id)) {
      return 1;
    }
    for (s32 table = 0; table < kTableCount; table++) {
      const u32 remapped = Sfx_Remap(table, id);
      if (remapped != id && Sfx_IsPlayingByIdVanilla(mgr, remapped)) {
        return 1;
      }
    }
    return 0;
  }
  }
}  // namespace rnd
